#!/usr/bin/env node
'use strict';

const buildRoutes = require('../site/routes');
const ReactDOMServer = require('react-dom/server');
const fs = require('fs');
const path = require('path');
const mkdirp = require('mkdirp');

function renderSite() {
  const template = fs.readFileSync(path.join(__dirname, '../site/template.html'), 'utf8');

  buildRoutes().forEach((p) => {

    const routePath = path.join(__dirname, '../', p.route);
    if (!fs.existsSync(routePath)) {
      mkdirp.sync(routePath);
    }

    fs.writeFileSync(path.join(routePath, 'index.html'),
      template.split('{content}').join(ReactDOMServer.renderToStaticMarkup(p.component))
    );
    console.log('Completed ' + p.name);
  });
}

module.exports = renderSite;

if (require.main === module) {
  renderSite();
}
