name: Basic Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install npm dependencies
        run: npm ci --no-fund --no-audit --prefer-offline

      - name: Test
        run: npm test
