name: Basic Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Configure CodeArtifact npm credentials
        uses: mapbox/gha@action-configure-codeartifact-credentials-v1
        with:
          repo-type: npm

      - name: Install npm dependencies
        run: npm ci --no-fund --no-audit --prefer-offline

      - name: Test
        run: npm test
